#!/usr/bin/env bash


db=1
err() {
	if (( $db )); then
		printf "$1" 1>&2
		fi
	}

path_prefix=""


#default config
card_preamble=""
card_postamble="</br>"
doc_preamble="<!doctype html><head><title>my cool site</title></head><body>"
doc_postamble="</body>"
ignore="index.html"
protected="false"

fetch_config(){
	local found=$(awk "/\["$1"\]/,/\[end\]/" .config) #pull the block with regex
	if [[ $found != "" ]]; then
		echo "${found}" | sed -e "s/^\[.*\]//" -e "s/\[end\]//" -e "s/[\\\.*]//" #if the block exists truncate the delimeters, escape remove \ used for escape
	else
		err "defaulting $1 to $2\n"
		echo "$2" #if the block doesnt exist give the default value provided
	fi
}
###
#HTML generation

make_card(){
	echo "$card_preamble"
	echo "<a class="card_link" href="${1}"> ${1} </a>"
	echo "$card_postamble"
}

make_index(){
	echo "$doc_preamble" > "index.html"
	for file in "${files[@]}"; do
		make_card "$file" >> "index.html"
	done
	echo "$doc_postamble" >> "index.html"
}

###
#recursive step

load_config_and_build(){
	err "load in $PWD\n"
	#load config
	if test -f ".config"; then #if theres no set config it'll just scope up
		err "load config\n"
		#if unconfigured inherit from parent config
		local card_preamble="$(fetch_config "card_preamble" "$card_preamble")"
		local card_postamble="$(fetch_config "card_postamble" "$card_postamble")"
		local doc_preamble="$(fetch_config "doc_preamble" "$doc_preamble")"
		local doc_postamble="$(fetch_config "doc_postamble" "$doc_postamble")"
		local protected="$(fetch_config "protected" "false")" #default to unprotected
		local ignore="$(fetch_config "ignore" "$ignore")"
		ignore=$(echo "${ignore:-^\$}" | grep -v "^$") #remove empty lines otherwise grep doesn't filter right
	fi

	#check for spaces in file/directory names
	spaces=$(ls | awk "/ /")
	err "space detection $spaces \n"
	if [[ $spaces != "" ]]; then
		echo "the following file(s) have spaces in the name, rename them and try again: ${spaces}"
		exit 1
	fi

	#get files and apply ignore
	err "ignoring: $ignore\n"
	local files=($(ls -p | grep -vF -- "$ignore"))
	err "detected: ${#files[@]}\n"
	if [[ "$protected" = "false" ]]; then
		err "making index\n"
		make_index
	fi
}

###
#recursion

recurse() {

	load_config_and_build

	err "continue to $(ls -d */ 2>/dev/null| grep -vF -- "$ignore")\n"
	for dir in $(ls -d */ 2>/dev/null| grep -vF -- "$ignore"); do
		old_path="$path_prefix"
		path_prefix="$path_prefix$dir"
		cd $dir
		err "recursing to $dir"
		recurse
		cd ..
		path_prefix="$old_path"
	done
}

###
#execution

if [[ $1 = "" ]]; then
	echo "hey you gotta give me a directory"
	exit 1
else
	cd $1
	recurse
	err "bye\n"
fi
