#!/usr/bin/env bash


db=0
err() {
	if (( $db )); then
		printf "$1" 1>&2
		fi
	}

path_prefix=""


#default config
card_preamble=""
card_postamble="</br>"
doc_preamble="<!doctype html><head><title>my cool site</title></head><body>"
doc_postamble="</body>"
ignore="index.html"
protected="false"

fetch_config(){
	local found=$(awk "/\["$1"\]/,/\[end\]/" .config) #pull the block with regex
	if [[ $found != "" ]]; then
		echo "${found}" | sed -e "s/\[.*\]//g" #if the block exists truncate the delimeters
	else
		echo $2 #if the block doesnt exist give the default value provided
	fi
}

make_card(){
	echo "$card_preamble"
	echo "<a class="card_link" href="${1}"> ${1} </a>"
	echo "$card_postamble"
}

make_index(){
	echo "$doc_preamble" > index.html
	for file in "${files[@]}"; do
		make_card "$file" >> index.html
	done
	echo "$doc_postamble" >> index.html
}

crawl(){
	err "crawl $PWD"
	#check config
	if test -f ".config"; then #if theres no set config it'll just scope up
		err "load config\n"
		#if unconfigured inherit from parent config
		local card_preamble="$(fetch_config card_preamble "$card_preamble")"
		local card_postamble="$(fetch_config card_postamble "$card_postamble")"
		local doc_preamble="$(fetch_config doc_preamble "$doc_preamble")"
		local doc_postamble="$(fetch_config doc_postamble "$doc_postamble")"
		local ignore="$(fetch_config ignore "$ignore")"
		ignore=$(echo "$ignore" | grep -v "^$") #remove empty lines otherwise grep doesn't filter right
		local protected="$(fetch_config protected false)" #default to unprotected
	fi

	files=($(ls -p | grep -vF "${ignore:-"\^\$"}"))
	err "detected: \n$files"
	if [[ "$protected" = "false" ]]; then
		make_index
	fi

	for dir in $(ls -d */ | grep -vF "$ignore"); do
		old_path="$path_prefix"
		path_prefix="$path_prefix$dir"
		cd $dir
		crawl .
		cd ..
		path_prefix="$old_path"
	done
}

if [[ $1 = "" ]]; then
	echo "hey you gotta give me a directory"
else
	cd $1
	crawl
fi
